# Native PowerShell game-names builder (no Node.js required)
function Build-GameNamesFile {
    param([string]$Root, [string]$OutFile)

    $ScriptDir = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent (Get-Item 'd:\CG\scripts\build-game-names-core.ps1').FullName }
    $DataDir = Join-Path $ScriptDir 'data'
    $utf8 = New-Object System.Text.UTF8Encoding $false

    . (Join-Path $ScriptDir 'game-names-translate.ps1')

    $names = New-Object 'System.Collections.Generic.HashSet[string]'
    function Add([string]$n) { if ($n) { [void]$names.Add($n.Trim()) } }

    $eqRaw = [IO.File]::ReadAllText((Join-Path $Root 'equipment_catalog.js'), $utf8)
    [regex]::Matches($eqRaw, '"name":\s*"([^"]+)"') | ForEach-Object { Add $_.Groups[1].Value }

    function Walk-Pet($p) {
        Add $p.name
        if ($p.evolutions) { foreach ($e in $p.evolutions) { Walk-Pet $e } }
    }
    $pets = Get-Content (Join-Path $Root 'pets.json') -Raw -Encoding UTF8 | ConvertFrom-Json
    foreach ($p in $pets) { Walk-Pet $p }

    $html = [IO.File]::ReadAllText((Join-Path $Root 'StarCG_PriceChecker.html'), $utf8)
    if ($html -match 'const BOUNTY_EQUIPMENT = \{([\s\S]*?)\n\};') {
        $eqBlock = $Matches[1]
        [regex]::Matches($eqBlock, "\['(?:[^']*?)','([^']+)'\]") | ForEach-Object { Add $_.Groups[1].Value }
        [regex]::Matches($eqBlock, ":\s*\[([^\]]+)\]") | ForEach-Object {
            [regex]::Matches($_.Groups[1].Value, "'([^']+)'") | ForEach-Object {
                $v = $_.Groups[1].Value
                if ($v -notmatch '^(\d+[A-Z]?)$') { Add $v }
            }
        }
    }
    if ($html -match 'const BOUNTY_PETS = \{([\s\S]*?)\n\};') {
        [regex]::Matches($Matches[1], "\['Lv\d+','([^']+)'\]") | ForEach-Object { Add $_.Groups[1].Value }
    }
    foreach ($block in @('COMMON_ACCESSORIES','COMMON_POTIONS','COMMON_ENCHANTS')) {
        if ($html -match "const $block = \{([\s\S]*?)\n\};") {
            $blk = $Matches[1]
            [regex]::Matches($blk, "\['(?:[^']*?)','([^']+)'\]") | ForEach-Object { Add $_.Groups[1].Value }
            [regex]::Matches($blk, "'([^']+)'") | ForEach-Object {
                $v = $_.Groups[1].Value
                if ($v -notmatch '^(\d+[A-Z]?|Lv\d+)$' -and $v.Length -ge 2) { Add $v }
            }
        }
    }

    # Material single + bag (prefix U+4E00 U+888B)
    $bagPrefix = [string][char]0x4E00 + [char]0x888B
    foreach ($mb in @('MATERIAL_HUNT','MATERIAL_MINE','MATERIAL_WOOD')) {
        if ($html -match "const $mb = \[([\s\S]*?)\];") {
            [regex]::Matches($Matches[1], "\['Lv\d+','([^']+)'\]") | ForEach-Object {
                $v = $_.Groups[1].Value
                Add $v
                Add ($bagPrefix + $v)
            }
        }
    }

    # Gem tiers: build from gem type labels in gems_data.js (same patterns as GEM_TIER_NAMES)
    $gemsJs = [IO.File]::ReadAllText((Join-Path $Root 'gems_data.js'), $utf8)
    [regex]::Matches($gemsJs, "label:\s*'([^']+)'") | ForEach-Object { Add $_.Groups[1].Value }
    $gemLabels = @()
    if ($gemsJs -match 'GEM_TYPE_LABELS = \{([\s\S]*?)\};') {
        [regex]::Matches($Matches[1], ":\s*'([^']+)'") | ForEach-Object {
            $gemLabels += $_.Groups[1].Value
            Add $_.Groups[1].Value
        }
    }
    $pFragment = [string][char]0x7684 + [char]0x788E + [char]0x7247
    $pHeavy = [string][char]0x7834 + [char]0x640D + [char]0x7684 + [char]0x5F88 + [char]0x56B4 + [char]0x91CD + [char]0x7684
    $pBroken = [string][char]0x7834 + [char]0x7834 + [char]0x7684
    $pSlight = [string][char]0x6709 + [char]0x9EDE + [char]0x7834 + [char]0x640D + [char]0x7684
    $pDecent = [string][char]0x9084 + [char]0x4E0D + [char]0x932F + [char]0x7684
    $pFine = [string][char]0x512A + [char]0x826F + [char]0x7684
    $pVeryFine = [string][char]0x975E + [char]0x5E38 + [char]0x512A + [char]0x826F + [char]0x7684
    $pNear = [string][char]0x63A5 + [char]0x8FD1 + [char]0x5B8C + [char]0x7F8E + [char]0x7684
    $pPerfect = [string][char]0x5B8C + [char]0x5168 + [char]0x7ED3 + [char]0x6676 + [char]0x9AD4 + [char]0x7684
    foreach ($g in $gemLabels) {
        Add ($g + $pFragment)
        Add ($pHeavy + $g)
        Add ($pBroken + $g)
        Add ($pSlight + $g)
        Add $g
        Add ($pDecent + $g)
        Add ($pFine + $g)
        Add ($pVeryFine + $g)
        Add ($pNear + $g)
        Add ($pPerfect + $g)
    }

    Initialize-GameNameTranslators -DataDir $DataDir -Root $Root

    $sorted = @($names | Sort-Object { $_ })
    $lines = New-Object System.Collections.Generic.List[string]
    [void]$lines.Add('/**')
    [void]$lines.Add(' * Star CG game name i18n (zh -> en / ko)')
    [void]$lines.Add(' * Auto-generated by scripts/build-game-names.ps1 -- do not edit by hand')
    [void]$lines.Add(" * Generated: $((Get-Date).ToUniversalTime().ToString('o'))")
    [void]$lines.Add(" * Count: $($sorted.Count)")
    [void]$lines.Add(' */')
    [void]$lines.Add('(function (global) {')
    [void]$lines.Add("  'use strict';")
    [void]$lines.Add('  const MAP = {')
    foreach ($zh in $sorted) {
        $t = Translate-GameName $zh
        $eZh = Escape-GameNameJs $zh
        $eEn = Escape-GameNameJs $t.en
        $eKo = Escape-GameNameJs $t.ko
        [void]$lines.Add("    '$eZh': { en: '$eEn', ko: '$eKo' },")
    }
    [void]$lines.Add('  };')
    [void]$lines.Add("  if (global.StarCG_I18N && typeof global.StarCG_I18N.registerGameNames === 'function') {")
    [void]$lines.Add('    global.StarCG_I18N.registerGameNames(MAP);')
    [void]$lines.Add('  }')
    [void]$lines.Add("})(typeof globalThis !== 'undefined' ? globalThis : window);")
    [void]$lines.Add('')

    [IO.File]::WriteAllText($OutFile, ($lines -join [Environment]::NewLine), $utf8)
    Write-Host "Wrote $($sorted.Count) names to $OutFile"
}
